go-gorm/sqlite

migrator.go

This is a proposal. If you agree I can replace all the other `BEGIN` statements of this `Migrator` in the same PR.
It uses the gorm transaction logic properly instead of embedding a `BEGIN` / `COMMIT` inside a big transaction
While writing [a simple migration orchestration tool for Gorm](https://github.com/fclairamb/gorm-migrate) I realized that some migration commands couldn't be executed inside of a transaction with the sqlite implementation. 
As you know, this is a very common scenario for database management: You try to perform a migration possibly on multiple files and if it fails, you want to go back to the previous state.
Basycally as soon as you do something like the following code, you will be in trouble because it performs a big query with a `COMMIT` when one has already been …

Proper use of transaction in the sqlite migrator.

---

sqlite.go
sqlite_test.go

Much like the `mysql` driver's `DriverName`, this allows you to specify a custom driver for SQLite.  This is important when creating custom functions, for example.
I also added unit tests to cover these changes.
I frequently use SQLite in-memory databases for unit tests for my projects that use MySQL and Postgres in production.  Part of doing that is creating a custom SQLite driver that has some custom functions for parity with MySQL and Postgres (for example, `CONCAT` or `NOW`).
Because Gorm v2 does not directly specify the driver on the `Open` function anymore, this "driver" will need to be able to support it.  The `mysql` driver already does this, so this just brings this driver up to par with that one.

Allow custom drivers

---

sqlite.go

Accept existing connection from dialector
To keep parity across other drivers (mysql, pg) they already do this
When working with elastic-apm-go it uses its own driver to open connections and hence they are traceable.
We were able to pass the apm opened connections to mysql and pg since they already have this field in Dialector

take connection from dialector if available

---

sqlite.go

- I checked this patch at https://github.com/c-bata/goptuna/pull/171.
This PR is for automatically skipping FOR UPDATE (and FOR SHARE) clause.
See https://github.com/go-gorm/gorm/issues/3687 for details.
Currently, it is required to write following code:
```go
if s.db.Dialector.Name() == "sqlite" {
result = tx.First(&study, "study_id = ?", studyID)
} else {
result = tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&study, "study_id = ?", studyID)
}
```
https://github.com/c-bata/goptuna/blob/9e9699a4394bf94f2a311ba4574a507ac833c824/rdb.v2/storage.go#L216-L224
From this patch, we can write it like below:
```go
result = tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&study, "study_id = ?", studyID)
```

Ignore FOR UPDATE and FOR SHARE clause

---

migrator.go

The recent fix https://github.com/go-gorm/sqlite/commit/55a60eb3a1b26a3b4e908e3a43a8ad9c21254069 for https://github.com/go-gorm/sqlite/issues/7 introduced breaking **TestMigrateColumns** in GORM.
This is due to regex was concatenated from 2 strings, one containing ```[``` , second containing ```]```.
In output regex this was considered as character class (e.g. ```[abc]```).
This fix escapes ```[``` and ```]``` with backslash, so that it's interpreted by regex engine as intended.

patch for https://github.com/go-gorm/sqlite/issues/7

---

ddlmod.go
ddlmod_test.go

fix parseDDL bug with escaped quote, (This is probably a p0 level bug)
Data loss occurs when exec AutoMigrate!
reproduces:
> `gorm.io/driver/sqlite v1.3.1`
> `gorm.io/gorm v1.23.4`
1. run `AutoMigrate`, create users table
```go
package main
import (
"gorm.io/driver/sqlite"
"gorm.io/gorm"
"log"
)
type User struct {
ID int `json:"id" gorm:"primaryKey;"`
FirstName string `json:"first_name" gorm:"size:100;not null;default:''"`
LastName  string `json:"last_name" gorm:"size:100;not null;default:''"`
Age       int    `json:"age" gorm:"not null;default:0"`
}
func main() {
db, err := gorm.Open(sqlite.Open("/tmp/sqlite.db"), &gorm.Config{})
if err != nil {
panic("failed to connect database")
}
if err := db.AutoMigrate(&User{}); err != nil {
log.Println(err)
}
}
```
2. insert data `INSERT INTO …

fix parseDDL bug with escaped quote

---

ddlmod.go
ddlmod_test.go

parseDDL index out of range when characters take up more than one byte
Panic(index out of range) when sql like: ```CREATE TABLE `test` (`text` varchar(10) DEFAULT "测试，")```

fix: parseDDL index out of range

---

sqlite.go

- [] Do only one thing
- [] Non breaking API changes
- [] Tested

fix: limit=0 results (#5735)

---

ddlmod.go
ddlmod_test.go
migrator.go

This pull request fix this issue:
https://github.com/go-gorm/gorm/issues/5590
```
cannot INSERT into generated column
```
I just created another method for `ddl` called `getSafeColumns`. It did the exact work of `getColumns` except it ignore the GENERATED COLUMNS.
This is important for `recreateTable` of the Migrator.
```go
// Old
columns := createDDL.getColumns()
// New
columns := createDDL.getSafeColumns()
```

ignore generated columns when [recreateTable]

---

error_translator.go
go.mod
go.sum

This PR adds support for translating Sqlite errors like unique key violation to native gorm errors (ErrDuplicatedKey)
Related PR in gorm repo: https://github.com/go-gorm/gorm/pull/6004

feat: error translator support added

---

ddlmod.go
ddlmod_test.go

Get right unique index when parsing ddl `CREATE UNIQUE INDEX ...`
It has a little relationship with https://github.com/go-gorm/gorm/issues/6163.
( In that case, grom shouldn't AlterColumn, but it did because of the wrong unique value. 
Fixing [6163](https://github.com/go-gorm/gorm/issues/6163) requires additional work.
```sql
CREATE UNIQUE INDEX `idx_uq` ON `test-b`(`field`)
```
paseDDL => `field.UniqueValue` is true

fix parse unique index

---

sqlite.go

fix https://github.com/go-gorm/gorm/issues/6033
```go
type Test struct {
Date time.Time `gorm:"type:date"`
Time time.Time `gorm:"type:time"`
DefaultDateTime time.Time
}
```
```sql
CREATE TABLE `tests` (`date` date,`time` time,`default_date_time` datetime)
```

distinguish between schema.Time and tag time

---

error_translator.go

The new error translation functionality was depending on go-sqlite3 package types and since the go-sqlite3 is a cgo package it needs the CGO_ENABLED=1 flag required plus it will require new compilers like cross-C-compiler to be installed on the machine.
In this PR I reimplement the error translation and do not depend on go-sqlite3 package at all.

fix: dependency issue with go-sqlite3 package

---

ddlmod.go
ddlmod_test.go
migrator.go

Fixes two regex issues that prevented the proper parsing of SQL create statements. Fixes #139. For a more detailed description, please check the linked issue.

Fix two regexes related to SQL create statement parsing

---

error_translator.go
go.mod
go.sum

For better development the developer-friendly error ForeignKeyViolated has been implemented on the driver so it will translate all ForeignKeyViolatation errors to native gorm error ForeignKeyViolated.
Task 3 of the incomplete feature: https://github.com/go-gorm/gorm/issues/6345

feat: foreign key violation error

---

migrator.go

RenameIndex should drop old index.
It blocked https://github.com/go-gorm/gorm/pull/6303

fix: RenameIndex should drop old index

---

error_translator.go

Translate the SQLITE_CONSTRAINT_PRIMARYKEY error code to ErrDuplicatedKey as well for consistency.
We refactored our code to take advantage of ErrDuplicatedKey, but the tests fail because ErrDuplicatedKey only gets returned for non primary key fields (and it should IMO):
https://github.com/italia/developers-italia-api/pull/197
https://github.com/italia/developers-italia-api/actions/runs/5143820348/jobs/9259314436?pr=197
Also, should this go in https://github.com/go-gorm/postgres and https://github.com/go-gorm/mysql as well?

fix: translate SQLITE_CONSTRAINT_PRIMARYKEY to ErrDuplicatedKey

---

error_translator.go

ErrForeignKeyViolated error was not set up correctly with SQLITE_CONSTRAINT_FOREIGNKEY constant. Within this PR it is mapped to the right SQLITE_CONSTRAINT_FOREIGNKEY. https://www.sqlite.org/rescode.html#constraint_foreignkey

fix: ErrForeignKeyViolated error constant

---

ddlmod.go
ddlmod_test.go

Fixes an issue where the migrator determines that a column is unique (true) when referenced in an index DDL without further determining whether the index is unique.  As a result, a model with a non-unique index tag is always be deemed different than the DDL which always triggers a table migration.  The fix is to determine the column uniqueness based on whether the referencing index DDL is `CREATE UNIQUE INDEX ...` and not `CREATE INDEX`.
Set the `ColumnType.UniqueValue` based on the column being referenced in a UNIQUE index (not just any index).
Common use case of to add a non unique index on a foreign key to support cascade delete.  As a result, the auto-migrate detecting a difference and ALWAYS is migrating the table.
The use case: model defined as Person with `1-*` relation to Parent …

Fix columnType.Unique() returns true for non-unique index DDL.

---

ddlmod.go
migrator.go
sqlite.go

Fix #4760. Currently, sqlite dialector can't apply `AUTOINCREMENT` to the field type. The reason this method cannot work is if a field is marked as `AutoIncrement` and `PrimaryKey` at the same time, when we apply `AUTOINCREMENT` to data type, it will create SQL like the following:
```sql
CREATE TABLE `example_table` (`id` integer PRIMARY KEY AUTOINCREMENT, ..., PRIMARY KEY (`id`))'
```
This can cause `SQL logic error: table "example_table" has more than one primary key (1)` error, because there is two `PRIMARY KEY` definition in this statement. The root cause is `hasPrimaryKeyInDataType` doesn't check the result of `Dialector.DataTypeOf` method.
By checking the result of `Dialector.DataTypeOf` method, a dialector can define its behavior for `AUTOINCREMENT & PRIMARY KEY` situation.
The …

fix: AUTOINCREMENT flag cannot apply with PRIMARY KEY

---

ddlmod.go
ddlmod_test.go

This change sets the default value of ColumnType.Nullable() to true.
If the column is explicitly `NOT NULL` then it will be set false.
This is consistent with the SQLite documentation:
https://www.sqlitetutorial.net/sqlite-not-null-constraint/
Correct reporting of nullable state for a column that does not specify `NULL` explicitly

Issue #158 SQLite fields are nullible unless `NOT NULL`

---

ddlmod.go
ddlmod_test.go

indexRegex fix
cannot parse exists table with index when use:
`g.ApplyBasic(g.GenerateAllTable()...)`

fix ddl from exists table

---

ddlmod.go
ddlmod_test.go
go.mod
go.sum
migrator.go

See https://github.com/go-gorm/gorm/issues/6381.
based on https://github.com/go-gorm/gorm/pull/6386 and tested

refactor: distinguish between Unique and UniqueIndex

---

migrator.go

Using `%q` is not appropriate to quote a string literal in RAW SQL. Double-quoted strings are considered a [misfeature](https://www.sqlite.org/quirks.html#dblquote) of SQLite, and advised to be disabled at [compile time](https://www.sqlite.org/compile.html#dqs). Also, `%q` produces the _wrong_ quoting: `Hi "GORM"!` is quoted as `"Hi \"GORM\"!"` not `"Hi ""GORM""!"`, as SQLite would expect.
Current head fails GORM `TestMigrateWithUniqueIndexAndUnique` if SQLite is configured with `SQLITE_DQS=0`.

fix: double quoted string literals in migrator

---

sqlite.go

It adds a Config struct that can be used the same way the Postgres version can be. This allows a user to add their own driver instead of using the pre-defined one.
To use this with libSQL or Turso compatible SQLite

Added Config for custom driver (specifically libSQL)

---

go.mod
go.sum

Update go-sqlite3 to v1.14.22 (fixes #177)
Tested on Alpine 3.19.1
```
/home/alufers/Projects/Contrib/sqlite # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
/home/alufers/Projects/Contrib/sqlite # go build .
go: downloading gorm.io/gorm v1.25.7-0.20240204074919-46816ad31dde
go: downloading github.com/mattn/go-sqlite3 v1.14.22
go: downloading github.com/jinzhu/now v1.1.5
go: downloading github.com/jinzhu/inflection v1.0.0
/home/alufers/Projects/Contrib/sqlite #
```
Updating this library will fix building on Alpine. This is helpful for people building in containers.

Update go-sqlite3 to v1.14.22 (fixes #177)

---

ddlmod.go
ddlmod_parse_all_columns.go
ddlmod_parse_all_columns_test.go

This PR is a partial fix for issue #192.
- The current logic fails to parse multiple columns in PRIMARY KEY expressions (e.g., PRIMARY KEY (column1, column2)).
- It does not properly recognize certain column names, such as column,1.
- This PR addresses the first bug by improving the logic for parsing multiple columns within parentheses.
- The parseAllColumns function is now capable of correctly parsing column names, even when they are escaped, like `("column""1")`.
The second bug (handling of column names with commas) will be addressed in a separate PR, which is still in progress.
SQLite implements its escaping logic as follows:
https://github.com/sqlite/sqlite/blob/cf25c16a54f68d1ca095b91bd0ead840578b2bb4/ext/fts3/fts3.c#L464-L486
Refer test cases.

🐛 fix logic of parsing multiple columns (i.e. for PRIMARY KEYS, CONSTRAINT)
